= todo-list REST API Docs
송길주;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스

[[resources-index]]
== 인덱스

인덱스는 서비스 진입점을 제공한다.


[[resources-index-access]]
=== 인덱스 조회 (/api/)

`GET` 요청을 사용하여 인덱스에 접근할 수 있다.

operation::index[snippets='curl-request,links,http-response']

[[resources-todolist]]
== 할일

할일 리소스는 할일/목록 을 조회하거나 생성/수정/완료 할때 사용한다.

[[resources-todolist-all]]
=== 할일 목록 조회 (/api/todo)

`GET` 요청을 사용하여 모든 할일 목록을 조회할 수 있다.

operation::todo[snippets='curl-request,response-fields,links,http-response']


[[resources-todolist-id]]
=== 할일 조회 (/api/todo/{id})

`GET` 요청을 사용하여 {id}에 해당하는 할일을 조회할 수 있다.

operation::todo-id[snippets='curl-request,path-parameters,response-fields,links,http-response']

[[resources-todolist-create]]
=== 할일 추가 (/api/todo)

`POST` 요청을 사용하여 할일을 추가할 수 있다.

operation::todo-create[snippets='curl-request,request-fields,response-fields,links,http-response']

[[resources-todolist-update-content]]
=== 할일 내용 수정 (/api/todo/{id})

`PUT` 요청을 사용하여 할일 내용을 수정 할 수 있다.

operation::todo-update-content[snippets='curl-request,path-parameters,request-fields,response-fields,links,http-response']


[[resources-todolist-add-reference]]
=== 할일 참조 추가 (/api/todo/{id}/reference)

`PUT` 요청을 사용하여 할일을 참조 할 수 있다.

operation::todo-add-reference[snippets='curl-request,path-parameters,request-fields,response-fields,links,http-response']

[[resources-todolist-remove-reference]]
=== 할일 참조 제외 (/api/todo/{id}/reference)

`DELETE` 요청을 사용하여 참조한 할일을 제외할 수 있다.

operation::todo-remove-reference[snippets='curl-request,path-parameters,request-fields,response-fields,links,http-response']

[[resources-todolist-update-status]]
=== 할일 완료 처리 (상태변경) (/api/todo/{id}/status)

`PUT` 요청을 사용하여 할일 상태를 변경할 수 있다. (진행중, 완료, 삭제)

operation::todo-update-status[snippets='curl-request,path-parameters,request-fields,response-fields,links,http-response']